person_at_work = input("Enter your supervisor's name: ")
user_name = input("Enter your name: ")
body_part = input("Name a body part: ")
name_of_place1 = input("Name a place: ")
human_feeling = input("Enter a human feeling: ")
place_of_work = input("Enter a place of work: ")
medical_specialist = input("Choose a medical specialist: ")
name_of_place2 = input("Name a place: ")
name_of_verb = input("Choose a verb: ")
num_of_weeks = input("A random number: ")
time_value = input("Enter the time now:")
verb = input("Choose a verb: ")
activity_name = input("Enter an activity: ")
name_of_place3 = input("Name a place: ")
silly_email = input("Choose a silly email: ")
adjective = input("Choose an adjective (Describing word): ")
time_in_the_future = input("Choose a time in the future: ")


print("MadLib: Sick Note")
print("---------------------")
print("Hello", person_at_work, ", this is", user_name,".")
print("I think I've got that ",body_part ," virus that is going around ",name_of_place1,". ")
print("I'm ",human_feeling, ",but I can't come into ",place_of_work ," today. ")
print("My ", medical_specialist, " says I should stay at", name_of_place2, " and ", name_of_verb, " for up to ", num_of_weeks ," weeks.")
print("I will try to stop in by ", time_value," tomorrow, but if not, I'll ", verb, " and get some ", activity_name ,"done at ", name_of_place3 ,". ")
print("If you need me, you can reach me at ", silly_email,".")